executable     = /usr/bin/singularity

arguments      = exec --bind /work/rutger.vhaasteren/projects/combine-ptas/:/data/ --bind /work/rutger.vhaasteren/datasets/:/datasets/ --bind /tmp/:/tmp/ /work/rutger.vhaasteren/singularity_images/anpta.sif python /data/combine_ipta_pulsars.py --ipta_data_dir /datasets/IPTA-DR3 --procid $(ProcID) --output_dir /data/hdf5-pulsars/ipta-dr3-light/
#environment    = "MKL_NUM_THREADS=8; OPENBLAS_NUM_THREADS=8"

# Where to place output/logfiles
output         = out/job_output.$(ProcID).txt
error          = err/job_error.$(ProcID).txt
log            = job_log.txt

# which resources are needed
request_cpus     = 1
request_memory   = 4096
request_disk     = 1024000
accounting_group = pta.dev.first_tests

# How many jobs to start
queue 114
